version: "1"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: backendgang
      POSTGRES_PASSWORD: backendgang
      POSTGRES_DB: backend
      PGPORT: 8000
    ports:
      - 8000:8000

  db-manager:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: backend@backend.xyz
      PGADMIN_DEFAULT_PASSWORD: backend
    ports:
      - 8001:80

  wait-for-db:
    # check if database is up before execution of uvicorn
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:8000 -t 30s -i 500ms