# This github workflow runs tests with pytest

on:
  push:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8.8]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python
        run: sudo apt update && sudo apt-get install -y python3 python3-pip

      - name: Install dependencies
        run: python3 -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run unit tests
        run: python3 -m pytest
